.eslintrc.js, .github/workflows/checks.yml, .prettierrc, packages/client/jest.config.js, packages/client/package.json, packages/client/src/App.test.tsx, packages/client/src/App.tsx, packages/client/src/client.d.ts, packages/client/src/main.tsx, packages/client/src/vite-env.d.ts, packages/client/tsconfig.json, packages/client/vite.config.ts, packages/server/__tests__/example.test.ts, packages/server/db.ts, packages/server/index.ts, packages/server/jest.config.js, packages/server/package.json, packages/server/tsconfig.json, yarn.lock
Дополнены правила eslint и prettier.
Добавлены библиотеки antd, ant-design/icons и react-router-dom.
Добавлены алиасы для файловой структуры FSD.
=> Sprint 5/cof 43 configs

.eslintrc.js
Изменил правило на наименование enum с PascalCase на UPPER_CASE
Отредактировал файл .eslintrc.js
=> Изменил правило на наименование enum с PascalCase на UPPER_CASE

packages/client/package.json, packages/client/src/shared/components/PageLayout/PageLayout.css, packages/client/src/shared/components/PageLayout/PageLayout.tsx, yarn.lock
Добавила ErrorBoundary к контенту страницы для обработки ошибок
=> COF-62: Добавление ErrorBoundary к контенту страницы для обработки ошибок

packages/client/src/pages/Game/lib/GameScreens.tsx, packages/client/src/shared/components/Link/Link.css, packages/client/src/shared/components/Link/Link.models.ts, packages/client/src/shared/components/Link/Link.tsx, packages/client/src/shared/constants/game/types/ScreensEnum.ts, packages/client/src/shared/styles/ant/ant.css, packages/client/src/widgets/EndGameForm/index.ts, packages/client/src/widgets/EndGameForm/ui/EndGameForm.tsx, packages/client/src/widgets/GameCountdownForm/ui/GameCountdownForm.tsx
=> Sprint 5/cof 49

packages/client/src/main.tsx, packages/client/sw.js
Добавлен serviceWorker в приложение с использованием стратегии cache-first(сначала проверяется наличие кэша текущей версии приложения и при наличии он возвращается, если кэш отсутствует производится запрос на сервер).
Также, при наличии новой версии кэша - старая удаляется в "activate" ивенте. Для удобства локальной разработки используется флаг import.meta.env.PROD, который будет возвращать кэш только в прод окружении.
=> COF-89: Интеграция сервис воркера и кэширования приложения

README.md, packages/client/src/pages/Login/Login.tsx, packages/client/src/widgets/EndGameForm/ui/EndGameForm.tsx, yarn.lock
- Изменена ссылка на кнопку "Повторить игру"
- Исправлен текст на странице логина
=> Добавлена ссылка на видео с демонстрацией в README

packages/client/src/app/App.css, packages/client/src/app/App.test.tsx, packages/client/src/features/EditUserData/index.ts, packages/client/src/features/EditUserData/model/EditUserData.model.ts, packages/client/src/features/EditUserData/ui/EditUserDataForm.tsx, packages/client/src/features/EditUserData/ui/EditUserDataFormFields.tsx, packages/client/src/features/ImageLoader/ImageLoader.css, packages/client/src/features/ImageLoader/ImageLoader.tsx, packages/client/src/pages/Login/Login.tsx, packages/client/src/pages/Profile/Profile.css, packages/client/src/pages/Profile/Profile.tsx, packages/client/src/pages/Registration/Registration.tsx, packages/client/src/shared/api/api.ts, packages/client/src/shared/api/authApi/auth.interface.ts, packages/client/src/shared/api/authApi/authApi.ts, packages/client/src/shared/api/types/Api.models.ts, packages/client/src/shared/api/userApi/user.interface.ts, packages/client/src/shared/api/userApi/userApi.ts, packages/client/src/shared/lib/ValidationRules.ts, packages/client/src/shared/store/user/user.models.ts, packages/client/src/shared/store/user/userActions.ts, packages/client/src/shared/styles/ant/ant.config.ts, packages/client/src/shared/styles/ant/ant.css, packages/client/src/widgets/UserEdit/index.ts, packages/client/src/widgets/UserEdit/ui/UserEdit.tsx, packages/client/src/widgets/UserProfile/index.ts, packages/client/src/widgets/UserProfile/model/UserProfile.model.ts, packages/client/src/widgets/UserProfile/styles/UserProfile.css, packages/client/src/widgets/UserProfile/ui/UserProfile.tsx
https://linear.app/coffee-owls/issue/COF-60/sverstat-stranicu-polzovatelya
=> COF-60: Сверстать страницу пользователя

README.md, package.json, packages/client/index.html, packages/client/package.json, packages/client/src/app/App.test.tsx, packages/client/src/app/App.tsx, packages/client/src/entry-server.tsx, packages/client/src/main.tsx, packages/client/src/pages/Home/HomeSSR.tsx, packages/client/src/pages/Profile/Profile.tsx, packages/client/vite.config.ts, packages/server/index.ts, packages/server/package.json, packages/server/tsconfig.json
https://linear.app/coffee-owls/issue/COF-71/nastroit-express-dlya-server-side-rendering-bez-redux-prosto-otdavat
Запустить в дев режиме можно следующими командами:
- через  `"dev"` в `packages/server/package.json`
- через `"dev:server"`(`"lerna run dev --scope=server"`) в глобальном `package.json`
- через `"dev:ssr"` в `packages/client/package.json`
Запустить в режиме прода можно следующими командами:
- через  `"build"` и `"preview` в `packages/server/package.json`
- через `""build:ssr""` и `"preview:ssr"` в глобальном `package.json`
=> COF-71: Hастройка Express для Server Side Rendering

packages/client/src/features/AddForumTopicComment/ui/AddTopicCommentForm.tsx, packages/client/src/features/Reaction/index.ts, packages/client/src/features/Reaction/styles/Reaction.css, packages/client/src/features/Reaction/types/AddReaction.types.ts, packages/client/src/features/Reaction/ui/AddReaction.tsx, packages/client/src/features/Reaction/ui/PreviewReaction.tsx, packages/client/src/features/Reaction/ui/ReactionList.tsx, packages/client/src/pages/Forum/Forum.test.tsx, packages/client/src/pages/Forum/Forum.tsx, packages/client/src/pages/Topic/Topic.tsx, packages/client/src/shared/constants/forum/types/Forum.models.ts, packages/client/src/shared/constants/forum/types/Topic.models.ts, packages/client/src/shared/constants/forum/types/index.ts, packages/client/src/shared/store/forum/forum.models.ts, packages/client/src/shared/store/forum/forumSlice.ts, packages/client/src/shared/store/forum/mock.ts, packages/client/src/shared/store/store.ts, packages/client/src/shared/utils/delay.ts, packages/client/src/widgets/ForumTopicComments/ui/ForumTopicComments.css, packages/client/src/widgets/ForumTopicComments/ui/ForumTopicComments.tsx, packages/client/src/widgets/ForumTopicsTable/ui/ForumTopicsTable.tsx
https://linear.app/coffee-owls/issue/COF-47/emodzi-klientskaya-chast
API будет реализована в парной бэкэнд-задаче
Добавление эмодзи происходит по клику контекстного меню
=> COF-47: Эмодзи (клиентская часть)

packages/server/controllers/comment.controller.ts, packages/server/controllers/topic.controller.ts, packages/server/controllers/user.controller.ts, packages/server/index.ts, packages/server/init/index.ts, packages/server/mocks/index.ts, packages/server/models/comment.model.ts, packages/server/models/topic.model.ts, packages/server/models/types.ts, packages/server/models/user.model.ts, packages/server/package.json, packages/server/routes/forum.router.ts, packages/server/routes/index.ts, packages/server/swagger.yaml, packages/server/tsconfig.json, yarn.lock
Добавлено API для форума.
1. API описано в [swagger](https://app.swaggerhub.com/apis/IVANKOSTYULIN/CoffeeOwles/1.0.0#/)
2. Спроектирована структура базы данных
3. Определены модели Sequelize
4. Разработаны контроллеры с обработкой ошибок
5. Настроен роутер
Для пользователя также создана модель и контроллер. Предполагается, что после авторизации через API практикума мы будем проверять есть ли такой пользователь в нашей базе, и при отсутствии добавлять его. Также планируется реализовать механизм отслеживания изменений данных пользователя и автоматического их обновления в базе данных. Это позволит минимизировать частоту обращений к внешнему API практикума и поддерживать актуальные данные пользователей в локальной базе.
Так как реализация авторизации еще не готова, я замокал тестового …
=> COF-78: Реализовать API для форума

packages/client/src/features/AddForumTopic/ui/AddTopicForm.tsx, packages/client/src/pages/Forum/Forum.test.tsx, packages/client/src/pages/Forum/Forum.tsx, packages/client/src/pages/Topic/Topic.tsx, packages/client/src/shared/api/api.ts, packages/client/src/shared/api/authApi/authApi.ts, packages/client/src/shared/api/forumApi/forumApi.interface.ts, packages/client/src/shared/api/forumApi/forumApi.ts, packages/client/src/shared/api/leaderBoardApi/leaderBoardApi.ts, packages/client/src/shared/api/oauthApi/oauthApi.ts, packages/client/src/shared/api/userApi/userApi.ts, packages/client/src/shared/constants/forum/types/Forum.models.ts, packages/client/src/shared/constants/forum/types/Topic.models.ts, packages/client/src/shared/constants/forum/types/index.ts, packages/client/src/shared/store/forum/mock.ts, packages/client/src/widgets/ForumTopicComments/ui/ForumTopicComments.tsx
Добавил API и типизацию в соответствие со [swagger](https://app.swaggerhub.com/apis/IVANKOSTYULIN/CoffeeOwles/1.0.0#/)
Добавил предзагрузку данных и взаимодействие с redux
=> COF-81: Добавил поддержку API форума на клиенте

packages/client/src/main.tsx, packages/client/src/shared/components/PageFooter/PageFooter.css, packages/client/src/shared/components/PageFooter/PageFooter.tsx, packages/client/src/shared/components/PageHeader/PageHeader.css, packages/client/src/shared/components/PageHeader/PageHeader.tsx, packages/client/src/shared/components/ThemeProvider/ThemeProvider.tsx, packages/client/src/shared/enums/theme.ts, packages/client/src/shared/store/store.ts, packages/client/src/shared/store/themeSlice.ts, packages/client/src/shared/styles/ant/ant.config.ts
Необходимо добавить функционал переключения тем приложения на клиенте.
https://linear.app/coffee-owls/issue/COF-79/pereklyuchenie-tem-klientskaya-chast
Добавил в приложение темную тему, добавил кнопку для переключения темы.
=> COF-79: Переключение тем (клиентская часть)

packages/client/src/features/AddForumTopic/ui/AddTopicForm.tsx, packages/client/src/pages/Forum/Forum.tsx, packages/client/src/pages/Topic/Topic.tsx, packages/client/src/shared/api/forumApi/forumApi.interface.ts, packages/client/src/shared/store/forum/forumSlice.ts, packages/client/src/shared/store/forum/mock.ts, packages/client/src/widgets/ForumTopicsTable/ui/ForumTopicsTable.tsx, packages/client/src/widgets/LeaderBoardPanel/ui/LeaderBoardPanel.tsx, packages/client/src/widgets/LeaderBoardPanel/utils/SortLeaderBoardList.ts, packages/server/controllers/topic.controller.ts
=> fix: доработка функционала форума

README.md
=> Добавил видео демо 2

packages/client/src/pages/Forum/Forum.tsx, packages/client/src/pages/Topic/Topic.tsx, packages/client/src/shared/api/forumApi/forumApi.interface.ts, packages/client/src/shared/api/forumApi/forumApi.ts, packages/client/src/shared/store/forum/mock.ts, packages/client/src/widgets/ForumTopicHeader/ui/ForumTopicHeader.tsx, packages/client/src/widgets/ForumTopicsTable/ui/ForumTopicsTable.tsx, packages/server/controllers/topic.controller.ts
Исправлены типы API форума
Добавлены проверки на наличие данных
=> Исправлены типы API форума

packages/client/src/features/Reaction/ui/AddReaction.tsx, packages/client/src/features/Reaction/ui/PreviewReaction.tsx, packages/client/src/features/Reaction/ui/ReactionList.tsx, packages/client/src/features/Reaction/utils/isReactionModel.ts, packages/client/src/pages/Topic/Topic.tsx, packages/client/src/shared/api/forumApi/forumApi.interface.ts, packages/client/src/shared/api/forumApi/forumApi.ts, packages/client/src/shared/constants/forum/types/Forum.models.ts, packages/client/src/shared/constants/forum/types/Topic.models.ts, packages/client/src/shared/constants/forum/types/index.ts, packages/client/src/shared/store/forum/forumSlice.ts, packages/client/src/shared/store/forum/mock.ts, packages/client/src/shared/store/store.ts, packages/client/src/shared/store/topic/topic.model.ts, packages/client/src/shared/store/topic/topicSlice.ts, packages/client/src/widgets/ForumTopicComments/ui/ForumTopicComments.tsx, packages/server/controllers/reaction.controller.ts, packages/server/controllers/topic.controller.ts, packages/server/init/index.ts, packages/server/models/comment.model.ts, packages/server/models/reaction.model.ts, packages/server/models/types.ts, packages/server/routes/forum.router.ts
https://linear.app/coffee-owls/issue/COF-88/emodzi-bekend
=> COF-88: Эмодзи (бэкенд)

packages/client/public/sw.js, packages/client/src/main.tsx, packages/client/src/widgets/ForumTopicComments/ui/ForumTopicComments.tsx
Исправлена работа service worker для production окружения. sw отключен для dev окружения и для запросов помимо GET для избежания повтора отправки данных.
=> fix: исправлена работа sw для production

.github/workflows/build_and_push.yml, packages/client/src/shared/store/topic/topicSlice.ts
https://linear.app/coffee-owls/issue/COF-46/nastroit-action-dlya-avtodeploya
=> COF-46: Настроить Action для автодеплоя

.github/workflows/build_and_push.yml
=> fix(cof-46): удаление сборки клиента

.github/workflows/build_and_push.yml
=> fix(cof-46): Повышение версии ноды

packages/server/index.ts, packages/server/middlewares/csp.middleware.ts
https://linear.app/coffee-owls/issue/COF-87/dobavit-csp
Добавлена middleware для CSP.
В проекте нет статики которая берется из внешних ресурсов.
=> COF-87: Добавить CSP

packages/client/src/shared/styles/ant/ant.config.ts
Сравнение до/после прод версии и локального докер билда с фиксом
https://github.com/user-attachments/assets/afaf50be-d225-45f2-9536-1683e8fa825f
=> fix: исправлены стили в PROD окружении

packages/client/src/shared/utils/entry-server.utils.ts.ts, packages/server/index.ts
=> FIX: page init context

packages/client/src/shared/utils/entry-server.utils.ts.ts, packages/server/index.ts
=> Обновление main

packages/client/src/features/EditUserData/ui/EditUserDataForm.tsx, packages/client/src/features/ImageLoader/ImageLoader.tsx, packages/client/src/shared/api/userApi/userApi.ts, packages/server/controllers/user.controller.ts, packages/server/routes/index.ts
=> fix: доработка редактирования профиля
